# Project: 初见大程序
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = 初识大程序2.o 初识大程序1.o extern的使用，可在项目一个文件中使用其他文件的全局变量.o
LINKOBJ  = 初识大程序2.o 初识大程序1.o extern的使用，可在项目一个文件中使用其他文件的全局变量.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 初见大程序.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

初识大程序2.o: 初识大程序2.c
	$(CC) -c 初识大程序2.c -o 初识大程序2.o $(CFLAGS)

初识大程序1.o: 初识大程序1.c
	$(CC) -c 初识大程序1.c -o 初识大程序1.o $(CFLAGS)

extern的使用，可在项目一个文件中使用其他文件的全局变量.o: extern的使用，可在项目一个文件中使用其他文件的全局变量.c
	$(CC) -c extern的使用，可在项目一个文件中使用其他文件的全局变量.c -o extern的使用，可在项目一个文件中使用其他文件的全局变量.o $(CFLAGS)
